[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --minify --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.69.0"
  HUGO_ENV = "production"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://kind-euclid-df7a65.netlify.app/"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"